### ISSUE TITLE
new bill with amount >= 1000 results in invalid signature

### ISSUE THREAD

**Issue by tomblomfield-zz** [gocardless/gocardless-legacy-dotnet#1]
Amount 999 works fine, 1000 gives an invalid signature.

I suspect this is caused by differences in the way that typecasting between decimal and string are done.

Our server receives "amount"=>"1000.00"

**Comment by mcintyre321** [comment]
It looks like values over 999.99 were being written with commas - I've
changed this now so instead of =1,000.00 it is written to the URL as
=1000.00.

This doesn't account for  "amount"=>"1000.00"  however - for that to happen
the amount would have to be parsed to a number format, then re-interpreted
as a string. Is that the raw value that is coming in from the http server
log, or after processing by the api?

**Comment by timiles** [comment]
@tomblomfield, Harry's fix was also published last night to nuget as v1.0.2, so you can let your customer know to update to the latest version. Please let us know if this continues to be a problem.
